### ISSUE TITLE
Error with image after prediction

### ISSUE THREAD

**Issue by MT-Chuyen** [KhoiDOO/autoencoder#8]
Normally we expect that the predicted fundus image will show the blood vessels in white, with a black background.
But when executing the attunet code, I encountered a problem with the image after plotting, it has yellow blood vessels and a red background.

![issue with coldor](https://github.com/KhoiDOO/DecodeItAll/assets/114477110/3368ea80-93ed-4de1-ac91-bce832de168b)

**Comment by KhoiDOO** [comment]
Thanks Chuyen for updating the issue here, there are several things that we do need to check:
- Please check the model prediction shape, it should be whether ```(C=1, H, W)```, which means the output is a mask with one channel or ```(C = num distinguished value, H, W)``` in one hot channel format. 
- Please check the data shape fed into ```plt.imshow()``` function, it should be (H, W, C)

**Comment by KhoiDOO** [comment]
@MT-Chuyen is the issue over?
